sonar.organization=genesys-fatec
sonar.projectKey=genesys-fatec_API-4DSM-FRONTEND
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.exclusions=src/**/*.spec.ts,src/**/*.test.ts,src/**/*.d.ts
sonar.tests=tests
sonar.test.inclusions=tests/**/*.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info